#!/usr/bin/env python3
"""Generate src/prox_luts.h — the fixed-point lookup tables the v2.1 engine uses
instead of runtime transcendentals (engine spec v2.1 §7: "No FPU on hot paths:
any new log/exp/sqrt at tick rate is a defect; use the LUTs").

Run from anywhere:  python3 tools/gen_prox_luts.py
The output is checked in, so the firmware build has no Python dependency; re-run
this only when a table's definition changes.
"""

import math
import os

Q8 = 256.0
HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, os.pardir, "src", "prox_luts.h")

# N_eff at which thin-evidence discounting stops (== NEFF_TRAIN_MIN in proximity.h).
NEFF_FULL = 8


def rows(vals, per_line=8, width=6):
    out = []
    for i in range(0, len(vals), per_line):
        out.append("    " + " ".join(f"{v:>{width}}," for v in vals[i:i + per_line]))
    return "\n".join(out)


def logit8():
    # logit((score + 0.5) / 256), Q8. Score 0 -> -6.24 nats, 255 -> +6.24.
    return [int(round(Q8 * math.log((i + 0.5) / (255.5 - i)))) for i in range(256)]


def neff_gain():
    # g(N_eff) in [0,1] Q8: sqrt(min(1, n / NEFF_FULL)).
    # Indexed by the number of *newly independent* draws behind a tick, so g(0)
    # = 0 is load-bearing: a still wrist contributes no fresh draws and therefore
    # no fresh evidence, which is what makes a frozen fade unable to accumulate
    # false confidence (engine spec §1.3, §6.2).
    out = []
    for n in range(64):
        g = math.sqrt(min(1.0, n / float(NEFF_FULL)))
        out.append(min(256, int(round(Q8 * g))))
    return out


def logsumexp_corr():
    # log(1 + e^-d) in Q8, indexed by k = d_q8 >> 5 (step 1/8 nat, range 0..7.875).
    return [int(round(Q8 * math.log1p(math.exp(-(k * 32) / Q8)))) for k in range(64)]


def log2_mant():
    # log2(1 + i/64) in Q8 for the mantissa half of the integer log2 (§7 helper).
    return [int(round(Q8 * math.log2(1.0 + i / 64.0))) for i in range(64)]


def main():
    body = f"""// prox_luts.h — GENERATED by tools/gen_prox_luts.py. DO NOT EDIT BY HAND.
//
// Fixed-point tables for the v2.1 inference path. Every entry is Q8 (value * 256)
// unless noted. See proximity_engine_spec_v2.1.md §7 — the ESP32-C3 has no FPU,
// so the HMM/motion/integrator paths must contain no log/exp/sqrt at tick rate.

#ifndef PROX_LUTS_H
#define PROX_LUTS_H

#include <stdint.h>

// score (0..255) -> logit((score + 0.5)/256) in Q8 log-odds (engine spec §6.1).
static const int16_t PROX_LUT_LOGIT8[256] = {{
{rows(logit8())}
}};

// Newly-independent draws behind a tick (0..63, clamp above) -> evidence gain
// g in [0,1] Q8, = sqrt(min(1, n / {NEFF_FULL})). g(0) = 0 is deliberate: a tick
// that brought no fresh draw brings no fresh evidence (engine spec §1.3, §6.2).
static const uint16_t PROX_LUT_NEFF_GAIN[64] = {{
{rows(neff_gain())}
}};

// log(1 + e^-d) in Q8, indexed by k = |d_q8| >> 5 (step 1/8 nat, saturating at
// 7.875 nats where the correction is 0). The logsumexp tail (engine spec §6.2).
static const uint16_t PROX_LUT_LSE_CORR[64] = {{
{rows(logsumexp_corr())}
}};

// log2(1 + i/64) in Q8 — mantissa half of the integer log2 used to derive the
// per-tick transition constant from a time-scaled flip probability.
static const uint16_t PROX_LUT_LOG2_MANT[64] = {{
{rows(log2_mant())}
}};

#endif // PROX_LUTS_H
"""
    with open(OUT, "w") as f:
        f.write(body)
    print(f"wrote {os.path.normpath(OUT)}")


if __name__ == "__main__":
    main()
